sudo: false
language: node_js
node_js:
  - '0.10'

env:
  global:
    - secure: RmszqqyLfrQrzMwPYfeIrb1E9lqSEnuxx1y1fjcZ6gK+NOrUB9tpOFkOuOih2IpMWEalEVVhVPVKxN8q9xHOZvgLixWMG1BzI0UzkerUatfqbEzZj1qk9Y0aNI2OZZN/tl4C4NT5RamyLHcuXKxHX6xnWkGDaxSFmMFAmGMEADwA31fO+iCPg1pZ2ybZxFEEHq46Tg8jc9c9qSrT1FB5/Sh5fuLCjJ6Ms7jLxtbCIyPu9qJHw8615KLFtgjGwjp5FN7123cETiAL+KQQO41lhUPoi1Y4WAk1C4tAbs3m1yCHCywmurrzXpZhlCf+ejV7esBRJlbkebYxAAYrP2ZhA0ucgiExIGZInokcO3BNpSfsC39cjL00VXeaYzrq6rXhSFFtqw97U2rIeXkqqawLXU7vJV2c17kdlMYouBfHecD9FItuVyTi8fVzXYmGEoAatThVt0aLJKROAo9CO6eTHmQhLP+7mnwYcrcwDIOwD/Vhd8FUMi3iMEGJduFSLxRqT45v+fzIi7LJWmNTh7NDxmv+G8mKN5TzhSSv05rWlKZzMCTuKXD/8shCSNo4NZIfy/ro30Wx7knpbgRKw/JVWjrEHiWklNk6qWieZ3sbY3Rffb2Rh6xLufPMGJfAh8eW8VSLVjOoMqFEqXz6IXkZnBWfMwA2DqCv87eOhLcrMUw=
    - secure: ot8HESvGfe2Dl719bBvRj3JjDxp3usa4Jd2QtdoBsn/4n3Fz34jQIxoWwcoVaOInoqVoEU8cmb8yBpJQ+T54Ip4kbmmYPbXtlp9HnM/+KHs10iTkYukNnOxVo4CBbXXVwez/oi0bgt+4Sg0Z9j7u+fUoan5BLELUatiA5WXRnYRG0qo1zczQJecN8trdhnvgdi+0La7q89FgWpOB1fkPpq1CW1pWwsEPN8XYqus69sgb9zZMCiS63NJaTlztWEgwpVfxdY3x8PXpUgJ/tRh4UNVy4hIXvh5p6SKFD8g6UVbA/k8IPAjliNNFTGpeOudVCDgrylvLPQGn4AXCCtz9j9XNHR3vrSyCsIAYNUwAN6e83tgHfDbwlPV/znmd8+V7EDcSInGPefTzrrwkAu7qjk9VGoqS7dovZbCLeQUoNgk7YWDtWmCQ7RvJowGwAdrEhv6XCSthxx0cwlKGQ0Or+KbeU/bTlYZo5aFHSt1C4w0I9soISlqTGdtCKlY53X/IY75rMbIdwr2TBHJXuAFTV8/F4l01nXJKKTNLxWx2Nx+yj9tvMdr8JoQz03ni65WoybbPV/9d1yu17SOMGeXPC3xH5gi35gy9Skm15iKj4DJqD3NYycT0aE9vvPlIRLW2se4tqJkfdkNAkDf/y96P9lyjzBR69CTMeYro6dAeiow=
    - secure: h4i5gmn8suWrl6LMNJKwPsEL6t7ivlWhI26MLMG9JRdytL6ED1/cI64hzG3GODXW3LnloE2G/A9dJyOg49AVGKaB+yNL5TTtdRy7trF0oB6zgwPCXJeY74IYHQNGDm5iVHU5fLL3kLlx/MvPk3ECN0U+aA3glvS/phvIOK0pbrVPYJ2NzfldC7miZ10RF7dkcDPVzAgmQRzzhUbFjWAIRBRS23nm8Y9lTKu7u7nnN2teDO6++s94VcpScDrN7Z1Fbl8l0n7ZKv7i/HKr5pZhgydJCAqWb7h0YZ6V5e4q6yiN9gTlS4u82Qe5M96N8LOCdITlXxELBH5km4ZXHiA3xGEJHp2YGikxcssg/yWHxaTPC0Jew8tXyUWXGb78rjOZByS0zCnpH/12MCNQCrImV25fcmowlsVHdBdzjtGOGKfVKLiaIrJHt6OQwdZSIJYoHMzslOGRdrai/LvEDq4x0Awudg00RBzzf3Mdun6YrJJP1aHa8whWLZrkVzmKlXUYnN9bqMLcR4cOYFU3hzyPq95TSOXjG4/eyzw1yJckKTmlWM1r0TE89+U9jK+MCIpzUcFxBYWHjrKoyxEvGBlDo8ocRCr/uIdbW0v2dlEJFwobfraqKNIZo9bhV/m5QEAf8jwxkLOJXlQqMa7OcYZd6bT2Mjzp8uSGc1/+whi+5Sw=

before_install:
  - rm -rf node_modules/*
  - npm install -g npm
  - npm --version
  - npm config set loglevel warn
  - wget http://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip
  - unzip BrowserStackLocal-linux-x64.zip
  - ./BrowserStackLocal $BROWSER_STACK_ACCESS_KEY localhost,9876,0 > /dev/null &
  - sleep 10

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_script:
  - killall BrowserStackLocal

